/*MODELAGEM DE OFICINA*/
CREATE DATABASE OFICINA;

USE OFICINA;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE
);

/*CORRECAO*/
CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('COMERCIAL','RESIDENCIAL','CELULAR'),
    NUMERO VARCHAR(10),
    ID_CLIENTE INT,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

/*CORRECA*/
CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('COMERCIAL','RESIDENCIAL','CELULAR') NOT NULL,
    NUMERO VARCHAR(30) NOT NULL,
    ID_CLIENTE INT
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    ID_CLIENTE INT UNIQUE,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE CARRO(
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    CARRO VARCHAR(30) NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY(ID_CLIENTE)
    REFERENCES CLIENTE(IDCLIENTE)
);

/**/
CREATE TABLE CARRO(
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    CARRO VARCHAR(30) NOT NULL,
    ID_MARCA INT
);

CREATE TABLE COR(
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) NOT NULL,
    ID_CARRO INT,
    FOREIGN KEY(ID_CARRO)
    REFERENCES CARRO(IDCARRO)
);

/*CORRECAO*/
CREATE TABLE COR(
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) UNIQUE
);

CREATE TABLE MARCA(
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) NOT NULL,
    ID_CARRO INT,
    FOREIGN KEY(ID_CARRO)
    REFERENCES CARRO(IDCARRO)
);

/*CORRECAO*/
CREATE TABLE MARCA(
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(30) UNIQUE
);

/*CORRECAO*/
CREATE TABLE CARRO_COR(
    ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY(ID_CARRO,ID_COR)
);

/*CONSTRAINTS*/
ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

/**/
INSERT INTO ENDERECO VALUES(NULL,'RUA A','CENTRO','B. HORIZONTE','MG',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','CENTRO','RIO DE JANEIRO','RJ',2);

INSERT INTO CARRO VALUES(NULL,'CAMARO',1);
INSERT INTO CARRO VALUES(NULL,'A8',2);
INSERT INTO CARRO VALUES(NULL,'FUSCA',3);
INSERT INTO CARRO VALUES(NULL,'UNO',4);
INSERT INTO CARRO VALUES(NULL,'PALIO',4);
INSERT INTO CARRO VALUES(NULL,'GOL',3);
INSERT INTO CARRO VALUES(NULL,'MOBI',4);
INSERT INTO CARRO VALUES(NULL,'ARGO',4);
INSERT INTO CARRO VALUES(NULL,'POLO',3);
INSERT INTO CARRO VALUES(NULL,'AMAROK',1);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M',11);
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M',12);
INSERT INTO CLIENTE VALUES(NULL,'ANA','F',13);
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M',14);
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',15);
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F',16);
INSERT INTO CLIENTE VALUES(NULL,'MARILIA','F',17);
INSERT INTO CLIENTE VALUES(NULL,'LARISSA','F',18);
INSERT INTO CLIENTE VALUES(NULL,'NIVALDO','M',19);
INSERT INTO CLIENTE VALUES(NULL,'JOSE','M',20);

INSERT INTO TELEFONE VALUES(NULL,'CELULAR','9955331',2);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','12412412',3);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','3463463',4);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','321312312',7);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','967967967',2);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','5547474',6);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','4325235',2);
INSERT INTO TELEFONE VALUES(NULL,'COMERCIAL','412414',7);
INSERT INTO TELEFONE VALUES(NULL,'RESIDENCIAL','5475474',7);
INSERT INTO TELEFONE VALUES(NULL,'CELULAR','53453453',3);

INSERT INTO COR VALUES(NULL,'VERMELHO');
INSERT INTO COR VALUES(NULL,'AMARELO');
INSERT INTO COR VALUES(NULL,'VERDE');
INSERT INTO COR VALUES(NULL,'AZUL');
INSERT INTO COR VALUES(NULL,'PRETO');
INSERT INTO COR VALUES(NULL,'ROXO');
INSERT INTO COR VALUES(NULL,'BRANCO');
INSERT INTO COR VALUES(NULL,'GRAFITE');
INSERT INTO COR VALUES(NULL,'CINZA');
INSERT INTO COR VALUES(NULL,'ROSA');

INSERT INTO CARRO_COR VALUES(11,2);
INSERT INTO CARRO_COR VALUES(12,4);
INSERT INTO CARRO_COR VALUES(13,7);
INSERT INTO CARRO_COR VALUES(14,9);
INSERT INTO CARRO_COR VALUES(15,8);
INSERT INTO CARRO_COR VALUES(16,5);
INSERT INTO CARRO_COR VALUES(17,10);
INSERT INTO CARRO_COR VALUES(18,6);
INSERT INTO CARRO_COR VALUES(19,3);
INSERT INTO CARRO_COR VALUES(20,1);

INSERT INTO MARCA VALUES(NULL,'CHEVROLET');
INSERT INTO MARCA VALUES(NULL,'AUDI');
INSERT INTO MARCA VALUES(NULL,'VOLKSWAGEN');
INSERT INTO MARCA VALUES(NULL,'FIAT');
INSERT INTO MARCA VALUES(NULL,'FERRARI');
INSERT INTO MARCA VALUES(NULL,'PORSCHE');
INSERT INTO MARCA VALUES(NULL,'KIA');
INSERT INTO MARCA VALUES(NULL,'TESLA');
INSERT INTO MARCA VALUES(NULL,'HYUNDAI');
INSERT INTO MARCA VALUES(NULL,'JAGUAR');

/**/
SELECT NOME, SEXO, CARRO
FROM CLIENTE
INNER JOIN CARRO
ON IDCLIENTE = ID_CLIENTE
WHERE CARRO = 'CAMARO';